### ISSUE TITLE
项目进度(暂时只规划了alpha版本和beta版本,目前还在alpha阶段)

### ISSUE THREAD

**Issue by xiaomo1992** [flutter-jp/flutter_study_app#54]
- [进度总览](https://github.com/houko/flutter-study-app/projects)
- [alpha版本](https://github.com/houko/flutter-study-app/projects/1)
- [beta版本](https://github.com/houko/flutter-study-app/projects/2)

**Comment by houko** [comment]
234

**Comment by houko** [comment]
123123

**Comment by houko** [comment]
123123

**Comment by houko** [comment]
1
